<template>
  <div class="container">
    <div class="user_logged">
      <div class="user_block">
        <img
          class="img_user"
          src="https://api.adorable.io/avatars/285/abott@adorable.png"
          alt="Photo User"
        />
        <div class="user_indentify">
          <p class="name_user">Gustavo Jesus</p>
          <p class="profession_user">Developer</p>
        </div>

        <img class="img_edit" src="../assets/icons/icon_edit.svg" alt="" />
      </div>
    </div>

    <div class="generate_bill">
      <button class="btn_bill">
        <i class="icon-new_order"></i>Criar um novo boleto
      </button>
    </div>

    <div>
      <nav>
        <router-link :to="{name: 'Inbox'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-inbox"></i> Mensagens
          </span>
        </router-link>

        <router-link :to="{name: 'Alerts'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-bell"></i> Avisos
          </span>
        </router-link>

        <router-link :to="{name: 'Statistics'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-statistic"></i> Detalhes Recebimentos
          </span>
        </router-link>

        <router-link :to="{name: 'ManageStocks'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-gear"></i> Configuração de Empresa
          </span>
        </router-link>

        <router-link :to="{name: 'ManageSales'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-gear"></i> Controle de vendas
          </span>
        </router-link>
        <router-link :to="{name: 'ManageTaxes'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-gear"></i> Controle de Taxas
          </span>
        </router-link>
        <router-link :to="{name: 'ManageProducts'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-gear"></i> Controle de Produtos
          </span>
        </router-link>
        <router-link :to="{name: 'InventorySettings'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-settings"></i> Inventário
          </span>
        </router-link>
        <router-link :to="{name: 'Home'}" class="nav_item">
          <span class="item_icon">
            <i class="icon-off"></i> Sair
          </span>
        </router-link>
      </nav>
    </div>
  </div>
</template>

<script>
export default {
  name: "Sidebar",
  data() {
    return {};
  }
};
</script>

<style>
.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  overflow-x: auto;
}

.generate_bill {
  margin-top: 20px;
  margin-bottom: 20px;
}

.nav_item {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  width: 240px;
  height: 40px;
  margin-bottom: 10px;
  border-radius: 13px;
  border: none;
  font-family: "Acme", sans-serif;
  color: #a6acb8;
  background: transparent;
  cursor: pointer;
}

.router-link-exact-active {
  color: #fff;
  background-color: #04b075;
}

.user_logged {
  width: 100%;
  height: 100px;
  background: #ffffff;
  box-shadow: 0px 2px 4px rgba(92, 99, 105, 0.15);
  display: flex;
  align-items: center;
}

.img_user {
  border-radius: 50%;
  width: 60px;
  height: 60px;
  margin: 10px;
}

.name_user {
  font-family: "Acme", sans-serif;
  color: #1b262c;
  text-align: left;
  line-height: 0.2rem;
}

.profession_user {
  line-height: 0.2rem;
  font-family: "Acme", sans-serif;
  color: #a0a7b3;
  text-align: left;
}

.user_block {
  margin: auto;
  width: 240px;
  display: grid;
  align-items: center;
  grid-template-columns: 1fr 1.2fr 40px;
}
.img_edit {
  width: 20px;
  height: 20px;
}

li {
  list-style: none;
}

.btn_bill {
  width: 240px;
  height: 40px;
  border-radius: 13px;
  border: none;
  font-family: "Acme", sans-serif;
  color: #04b075;
  background: rgba(4, 176, 117, 0.2);
  cursor: pointer;
}

.btn_bill:active {
  background: #04b075;
  color: #fff;
  fill: #fff;
}

.item_icon {
  margin-left: 20px;
  width: auto;
}

/* width */
::-webkit-scrollbar {
  width: 3px;
}

/* Track */
::-webkit-scrollbar-track {
  background: #f1f1f1;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: #04b075;
  border-radius: 10px;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #555;
}

/* Generated by Glyphter (http://www.glyphter.com) on  Sun Mar 29 2020*/
@font-face {
  font-family: "Glyphter";
  src: url("../assets/fonts/Glyphter.eot");
  src: url("../assets/fonts/Glyphter.eot?#iefix") format("embedded-opentype"),
    url("../assets/fonts/Glyphter.woff") format("woff"),
    url("../assets/fonts/Glyphter.ttf") format("truetype"),
    url("../assets/fonts/Glyphter.svg#Glyphter") format("svg");
  font-weight: normal;
  font-style: normal;
}
[class*="icon-"]:before {
  display: inline-block;
  font-family: "Glyphter";
  font-style: normal;
  font-weight: bold;
  font-size: 1rem;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.icon-inbox:before {
  content: "\0041";
  margin-right: 10px;
}
.icon-gear:before {
  content: "\0042";
  margin-right: 10px;
}
.icon-bell:before {
  content: "\0043";
  margin-right: 10px;
}
.icon-off:before {
  content: "\0044";
  margin-right: 10px;
}
.icon-settings:before {
  content: "\0045";
  margin-right: 10px;
}
.icon-new_order:before {
  content: "\0046";
  margin-right: 10px;
}
.icon-statistic:before {
  content: "\0047";
  margin-right: 10px;
}
</style>